name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

# The latest macos version on GithubAction runner is macOS-11, but it fails xctests that contains swift.concurrency(linking issue?)
# ubuntu is stable for testing.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1
      with:
        swift-version: "5.5.2"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
